services:
  - type: web
    name: hospital-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hospital_system:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16